### ISSUE TITLE
Stronghold 

### ISSUE THREAD

**Issue by KekkyShmekky** [Earu/EasyChat#10]
[>KEKSQUAD|3|STEAM_0:1:23860033] Lua Error:
[ERROR] lua/easychat/modules/client/chatsoundsdocking.lua:10: attempt to index field 'StartChat' (a nil value)
1. fn - lua/easychat/modules/client/chatsoundsdocking.lua:10
2. Run - addons/ulib/lua/ulib/shared/hook.lua:109
3. ECOpen - lua/easychat/easychat.lua:252
4. fn - lua/easychat/easychat.lua:728
5. unknown - addons/ulib/lua/ulib/shared/hook.lua:109

Does this whenever a chat is opened/joining in.

**Comment by Earu** [comment]
Just got this fixed in [latest commit](https://github.com/Earu/EasyChat/commit/790a931177bad64f832d148119ea88fb9bc4ce99) sorry for the delay.
