### ISSUE TITLE
EasyChat does not allow you to properly hide chat

### ISSUE THREAD

**Issue by NovaAstral** [Earu/EasyChat#110]
Using the 'PlayerSay' hook to hide chat with this addon installed (for example, hiding messages that begin with "/") does not send the chat message at all, which means you cannot hide command usage using an addon.

**Comment by NovaAstral** [comment]
In my case, using
`hook.Add("PlayerSay","NVCmdHide",function(ply,text)
	if(string.StartWith(text,"/")) then
        return ""
	end
end)` in an addon to hide chats starting with /, hides it, but other addons, in this case Wiremod with Expression 2, cannot read the message sent with easychat installed

**Comment by NovaAstral** [comment]
I'm not sure how to use them, I'm not exactly good at coding, just somewhat decent

**Comment by Earu** [comment]
Hi, seems to me what you want to do is hide after sending the mssage? If so you should look at `OnPlayerChat`, this is called after all the networking is done and the clients receive the message. It's also vanilla so it should work without EC too.

**Comment by NovaAstral** [comment]
Thank you that worked
