### ISSUE TITLE
EasyChat Error message

### ISSUE THREAD

**Issue by SpielStern6000** [Earu/EasyChat#113]
`lua/gware-utils/sh_command_handler.lua:43: attempt to call field 'OnServerSideCalled' (a nil value)
stack traceback:
    addons/easychat/lua/easychat/easychat.lua:98: in function 'OnServerSideCalled'
    lua/gware-utils/sh_command_handler.lua:43: in function 'Run'
    lua/gware-utils/sh_command_handler.lua:79: in function 'fn'
    addons/rlib/lua/includes/modules/hook.lua:262: in function <addons/rlib/lua/includes/modules/hook.lua:239>
    [C]: in function 'xpcall'
    addons/easychat/lua/easychat/easychat.lua:97: in function 'SafeHookRun'
    addons/easychat/lua/easychat/networking.lua:456: in function 'SendGlobalMessage'
    addons/easychat/lua/easychat/easychat.lua:605: in function 'Callback'
    addons/easychat/lua/easychat/easychat.lua:2291: in function 'OnEnter'
    addons/easychat/lua/easychat/client/vgui/textentryx.lua:87: in function <addons/easychat/lua/easychat/client/vgui/textentryx.lua:82>[Akt] Jonas Wolf a`
    
    The error occurred when using GWare, a roleplay addon that is mainly responsible for adding commands like /akt /funk and so on.

**Comment by Earu** [comment]
Right so from this error trace, its quite obvious "gware" is breaking. EasyChat shows up there because its responsible for the chat, generally whenever youll have any error related to messages or the chat even if EasyChat is fine it will show up in the error.

Nothing I can do here.

**Comment by Earu** [comment]
Closing this as there is nothing further I can do.
