### ISSUE TITLE
Keyboard shortcuts on non-english layouts not working properly

### ISSUE THREAD

**Issue by MeteorTheLizard** [Earu/EasyChat#118]
On a german keyboard layout you cannot type "{", "}", "[", "]", etc. Into the chatbox or Lua tab as they require both LCONTROL and LALT to be pressed which does not seem to be supported.

**Comment by jule14** [comment]
for chatbox enabling easychat_legacy_entry should do it
afaik lua tab can't be fixed

**Comment by MeteorTheLizard** [comment]
> easychat_legacy_entry 1

Appears to be working for the main chatbox. I will be opening a separate issue for the lua tab as it was moved to a different repository.

**Comment by Earu** [comment]
Hi, please refer to this issue

https://github.com/Earu/EasyChat/issues/29
