### ISSUE TITLE
Problem with chat showing team

### ISSUE THREAD

**Issue by M3RCYXD** [Earu/EasyChat#121]
So in the settings I changed it to show the players team when chat, but when I enter something it shows the rank of the admin and then the players name in the Color of there job, but has no team name, there is also a box in the background of the chat, it only shows so much but is there a way for it not to show ?

**Comment by Earu** [comment]
Thats because it uses usergroup and not team names, to be specific you would like to see the actual team names I suppose? @M3RCYXD

**Comment by Earu** [comment]
Closing because issue is stale.
