### ISSUE TITLE
Imgur Token is expired

### ISSUE THREAD

**Issue by SergeyZet1** [Earu/EasyChat#122]
### How to reproduce bug

When player tries to upload some image in EasyChat via ctrl+v, he receives error 429/503 in console.

![image](https://github.com/Earu/EasyChat/assets/19843004/1b3747e8-3fd9-4f9f-921f-d7c97a222dca)

### Solution

Need to change Imgur token in this line
https://github.com/Earu/EasyChat/blob/4f8e8564f13d96850cd123814d2591c13959b84b/lua/easychat/easychat.lua#L1141

**Comment by Earu** [comment]
https://github.com/Earu/EasyChat/commit/36d6e843b5762fe7fe67419376b8780d6276822d

Changed the client id, can you tell me whether that changes anything for you? 
I haven't tested this at all, but I've been told the imgur API has been changed so maybe its a bit more complicated than changing the client id.
