### ISSUE TITLE
Images embed from untrustworthy websites

### ISSUE THREAD

**Issue by unknao** [Earu/EasyChat#123]
Title

**Comment by unknao** [comment]
It shouldn't be my responsibility to comb through every addon to see if its secure or not, also pac3 not having a website whitelist is an issue as well.

**Comment by unknao** [comment]
Also comparing anything to pac3 as if it's an example to be followed... lol

**Comment by unknao** [comment]
I'm sure that if you argue in circles some more and say nothing of value that will validate your position on allowing ip grabbing that you are opted in to by default.

**Comment by jule14** [comment]
> I'm sure that if you argue in circles some more and say nothing of value that will validate your position on allowing ip grabbing that you are opted in to by default.

i know that you have the extravagant urge to annoy children on gmod servers but if it leads to being a target of them ie. this issue then maybe it's best not to 😄

**Comment by Earu** [comment]
On a more serious note, I've been aware of this for the longest time but there's no reasonable solution for this. Let me explain why:

- whitelist
If I implement a whitelist it would mean I have to maintain a giant table with a bunch of domains which frankly I'm not too much into. The other very apparent issue is that as soon as I do that I will get 9999 questions and issues about "why images don't work anymore?"

- proxy/hosting content
That would mean storing a bunch of non sense on a server which would be costly and also a legal liability. People tend to share all kinds of bad stuff on the internet 

- disabling images by default 
It's already partially the case but it's more of a way to protect people from nsfw/trash content by blurring the images. Although I could straight out not show them id be back with tons of questions and issues "why images no work?"


So ultimately what would probably work is letting the user decide what is trustworthy or not, but I feel like this is more of a client issue than a EasyChat issue.

**Comment by Earu** [comment]
Closing as issue is stale and no fix / proper solution in sight.
