### ISSUE TITLE
New way to hide game menu via OnPauseMenuShow

### ISSUE THREAD

**Issue by SergeyZet1** [Earu/EasyChat#124]
In new update of Garry's Mod was added a hook [OnPauseMenuShow](https://wiki.facepunch.com/gmod/GM:OnPauseMenuShow). Could you please implement this feature into the chat?

**Comment by Earu** [comment]
Hi, I'm not sure what's there to do here?

**Comment by SergeyZet1** [comment]
https://github.com/Earu/EasyChat/blob/36d6e843b5762fe7fe67419376b8780d6276822d/lua/easychat/easychat.lua#L2691

This code fragment can be replaced by new hook [OnPauseMenuShow](https://wiki.facepunch.com/gmod/GM:OnPauseMenuShow) like that:

```lua
hook.Add("OnPauseMenuShow", TAG, function()
    if IsValid(EasyChat.Settings) and EasyChat.Settings:IsVisible() then
        EasyChat.Settings:SetVisible(false)
	return
     end

     if EasyChat.IsOpened() then
	    close_chatbox()
	    return false
     end
end)
```

Reasons:
1) It's more optimized than hook PreRender. 
2) [gui.HideGameUI()](https://wiki.facepunch.com/gmod/gui.HideGameUI) is deprecated

**Comment by Earu** [comment]
Pull requests are opened in that case!

**Comment by SergeyZet1** [comment]
Ok, i created the [pull request](https://github.com/Earu/EasyChat/pull/125)
