### ISSUE TITLE
ChatHUD/Chat history seem to randomly break

### ISSUE THREAD

**Issue by Tenrys** [Earu/EasyChat#14]
text max width seemed to have lowered itself and sometimes froze the client for a bit
![image](https://user-images.githubusercontent.com/3979239/45592440-bb50ab00-b96d-11e8-8fb1-78e33ebd0907.png)

link parsing broke somehow, also froze client for a bit
![image](https://user-images.githubusercontent.com/3979239/45592442-bf7cc880-b96d-11e8-85b5-1771059730bb.png)

**Comment by Cynosphere** [comment]
ChatHUD issue was never properly fixed, it just seemed to "go away" or was mitigated somehow but when I was moving it off of using a derma element I found the culprate

https://github.com/Earu/EasyChat/blob/master/lua/easychat/client/chathud.lua#L158

Font was never set when checking the text size.
