### ISSUE TITLE
Use derma skin colors instead of defaulting to black when using "Use Derma Skin"

### ISSUE THREAD

**Issue by Cynosphere** [Earu/EasyChat#19]
Themer users wouldnt be able to read text if they used a dark derma skin, which most users probably would.

**Comment by Cynosphere** [comment]
dm_tab.lua: Lines 109, 113, 190

**Comment by Earu** [comment]
Fixed in https://github.com/Earu/EasyChat/commit/b41a878f4f2698d1d407f9cf1d1b219d42e503a9
