### ISSUE TITLE
TextEntryX has poor performance when holding down keys

### ISSUE THREAD

**Issue by Cynosphere** [Earu/EasyChat#24]
![Demo](https://totallynotavir.us/i/xtfz6zsx.gif)

**Comment by Earu** [comment]
@Cynosphere is this fixed with the new changes ?

**Comment by Cynosphere** [comment]
It doesnt skip characters as much now but it also still lags a bit up to a certain extent which I'm speculating to be an issue with chatsounds more than the chatbox.
