### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by Earu** [Earu/EasyChat#28]
### General
- [x] aowl/ULX auto-complete (help?) support ([reference here](https://steamuserimages-a.akamaihd.net/ugc/856095852126730770/1D4957FC6C7F8A76E160BFFBFD232572C3AC6EB6/))
- [x] built-in color sets for customization
- [x] auto-translation of messages in the chat (ex: ru -> en)
- [x] settings pos x, y and width of chathud
- ~~[ ] setting to show player avatars~~
- [x] team server configuration (should override client setting?) ([reference here](https://media.gmodstore.com/_/script_media/254d765a59f6db73ea95ee40fc810a6c.png))
- [x] rate-limiting messages (anti-spam) @Python1320
- [x] auto-completion peeking (preview)
- [x] color picker
- [x] make sure not to show auto-completion for commands if FAdmin is detected
- [x] add a way to add words that mention you (mention filter?)

### Admin & DM Tabs
- ~~[ ] rework/merge into a more advanced "chatrooms" tab where admins is a default chatroom~~
- [x] DarkRP admin chat needs to be routed into the admin chat tab

**Comment by Oyplap** [comment]
Could you perhaps add rank prefix so that i can see my admin/mod/etc rank in the chat?

**Comment by Earu** [comment]
It already exists, its available in settings, ranks

**Comment by Oyplap** [comment]
I’m so dumb, sorry for bothering

**Comment by Earu** [comment]
No problem.
