### ISSUE TITLE
Using polish characters

### ISSUE THREAD

**Issue by Freszmun** [Earu/EasyChat#29]
How can I enable writing characters like ś,ć,ą,...

**Comment by Earu** [comment]
@Freszmun hey there, this is a recent issue due to a chromium update, more details here: https://github.com/Facepunch/garrysmod-issues/issues/4414

In the meantime you can use `easychat_legacy_entry 1` in the console

**Comment by Freszmun** [comment]
Sorry for very long response time. It works. Thanks!
