### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by Oyplap** [Earu/EasyChat#41]
How can i disable colors for all players except admins/mods/higher priority users?

**Comment by Earu** [comment]
You cannot at the moment, I'll look into adding it as an option for the server config.

**Comment by Oyplap** [comment]
Thank you!

Could you also add that for shaking text/rainbox/etc because people can spam and abuse it at this point

**Comment by Earu** [comment]
I was thinking of making the option disable or allow tags in names at all

**Comment by Earu** [comment]
https://github.com/Earu/EasyChat/commit/01b7f6ea05d12556606511ffe66c43d1ec92977d
I've added two settings under the chathud category:
- Allow tags in names
- Allow tags in messages

Only admins can edit these; they'll prevent people from using chat tags at all if disabled.
