### ISSUE TITLE
EasyChat opens regardless of Wire keyboard input lock settings

### ISSUE THREAD

**Issue by mavain** [Earu/EasyChat#42]
EasyChat will open even when using a Wire keyboard with `Lock player controls with keyboard` option enabled

**Comment by Earu** [comment]
For reference here are the two things that are conflicting:

Wire keyboard:
```lua
		hook.Add("PlayerBindPress", "wire_keyboard_blockinput", function(ply, bind, pressed)
			-- return true for all keys except the mouse, to block keyboard actions while typing
			if bind == "+attack" then return nil end
			if bind == "+attack2" then return nil end

			return true
		end)
```

EasyChat:
```lua
		hook.Add("PlayerBindPress", TAG, function(ply, bind, pressed)
			if not pressed then return end

			if bind == "messagemode" then
				open_chatbox(false, key_to_chat_mode())
				return true
			elseif bind == "messagemode2" then
				open_chatbox(true)
				return true
			end
		end)
```

What's happening here is that the wire keyboard is preventing any input, but EasyChat's hook is still ran and it opens the chat obviously as it should. Now I'm not sure what to do with this, I'm definitely not implementing wiremod checks in EasyChat's main code.
