### ISSUE TITLE
Make command autocomplete more of an API

### ISSUE THREAD

**Issue by Cynosphere** [Earu/EasyChat#43]
Would be nice to have an API for admin mods and what not to add to instead of hardcoding every single admin mod into the base or doing "hacks" to be identified as another admin mod.

**Comment by Cynosphere** [comment]
Also maybe being able to register multiple lookup tables, because ChatCommands list isn't really apart of aowl, even though Metastruct uses it the most outside of Outfitter.

**Comment by Earu** [comment]
It's not exactly in my plans at the moment, but if you do make a pull request I'll gladly merge it.
