### ISSUE TITLE
Chat tags aren't rendered when chat is opened

### ISSUE THREAD

**Issue by bloodless2010** [Earu/EasyChat#44]
Unsure if this is intended or not, but when I open the chat UI I see the following:
`blobles: <color=153,0,0>test`

But closed, it renders as `blobles: test` but with 'test' in a dark red, as intended. Running the most recent version.

**Comment by Earu** [comment]
That's intented, for two reasons:
- Parsing and rendering these tags in real-time is a very expensive operation meaning your FPS are likely to struggle a lot if it was to render your whole chat session history.
- Help people learn about chat tags via others. So they don't need to ask "how do I do X or Y" they can just open the chat and they'll see how the other did it.
