### ISSUE TITLE
server_config.lua:247: attempt to call field 'GetTab' (a nil value)

### ISSUE THREAD

**Issue by Bryantdl7** [Earu/EasyChat#46]
[EasyChat] lua/easychat/server_config.lua:247: attempt to call field 'GetTab' (a nil value)
  1. process_tabs_config - lua/easychat/server_config.lua:247
   2. func - lua/easychat/server_config.lua:277
    3. unknown - lua/includes/extensions/net.lua:32

This was displayed in my RCON window for my server. I unfortunately do not have repro steps available at this time.

**Comment by Earu** [comment]
@Bryantdl7 sorry for the delay I got busy with other things lately. I've pushed an update that might mitigate this issue you are having please do tell me if that issue happens again as I'm unsure if that fixed your issue since I cannot reproduce it.

**Comment by Earu** [comment]
Fixed (?)
