### ISSUE TITLE
Yandex Translate API no longer gives free keys

### ISSUE THREAD

**Issue by RanchTheDeer** [Earu/EasyChat#60]
The included auto-translator uses the Yandex translate API, of which the free service has been discontinued for users.
![image](https://user-images.githubusercontent.com/62909681/104572007-9a86e600-564b-11eb-96d2-465b6541ddd5.png)
Perhaps switching to an alternative API is an option? I'm not familiar with translation APIs myself so I couldn't give any recommendations. I know this would probably mean rewriting the way the addon handles the translate requests, but I still think the translate feature is very useful to have, especially when integrated into the addon like it is.
Perhaps something along the lines of LibreTranslate would be preferable?
https://libretranslate.com/

**Comment by Earu** [comment]
Yes it has been the case for a while now, there wasn't any proper alternative that we could find. But maybe your suggestion will work? I'll look into it.

**Comment by Cynosphere** [comment]
:/
![image](https://user-images.githubusercontent.com/1606710/104773005-9af9ac80-5731-11eb-846b-a6ba198e184a.png)

Yeah its self hostable, but then that becomes a liability.

**Comment by Earu** [comment]
> 
> 
> :/
> ![image](https://user-images.githubusercontent.com/1606710/104773005-9af9ac80-5731-11eb-846b-a6ba198e184a.png)
> 
> Yeah its self hostable, but then that becomes a liability.

Oh then if that's the case I don't personally want to host it. I want EasyChat to continue living without having to maintain services like that. What if I get even more busy than I am currently ? Nobody is gonna be there to maintain it anymore. So the more independent it is, the better.

If you do have more free public APIs that we can use though, feel free to post them here 👍

**Comment by Piehthyte** [comment]
Google translate API is usable and free. I haven't had a problem with it. I wrote an AutoHotkey script to do autotranslations cause I talk to a loooooooooot of non-English speakers. It should work for you as well.

**Comment by RanchTheDeer** [comment]
> 
> 
> Google translate API is usable and free. I haven't had a problem with it. I wrote an AutoHotkey script to do autotranslations cause I talk to a loooooooooot of non-English speakers. It should work for you as well.

The Google Translate API is *not* free by any stretch of the imagination. The user accessible one on the Google Translate website is, but not the backend API. Creation of a bot that uses the frontend as if it were a user violates Google's Terms of Service and would result in a hell of a lot of problems, mainly legal ones.
![image](https://user-images.githubusercontent.com/62909681/104824456-adffa000-5849-11eb-90ae-7cb95407ba28.png)

**Comment by RanchTheDeer** [comment]
Update: I've been looking around, and it looks like the Watson Translate API may be a viable alternative:
![image](https://user-images.githubusercontent.com/62909681/104824643-7abe1080-584b-11eb-8316-a6e9e8ed2479.png)

They claim that their free plans will remain free and won't charge you unless you explicitly opt-in to having a paid service. I'm not sure what 1 million characters works out to, but it's better than nothing.
The only requirement to use the API is to sign up for an account.

**Comment by Earu** [comment]
> 
> 
> Update: I've been looking around, and it looks like the Watson Translate API may be a viable alternative:~
> https://cloud.ibm.com/catalog/services/language-translator
> ![image](https://user-images.githubusercontent.com/62909681/104824643-7abe1080-584b-11eb-8316-a6e9e8ed2479.png)
> 
> They claim that their free plans will remain free and won't charge you unless you explicitly opt-in to having a paid service. I'm not sure what 1 million characters works out to, (mathematically, that's ~233,000 characters per week or ~33,000 characters per day
> The only requirement to use the API is to sign up for an account.

Sounds like a plan, I'll check it out eventually. I've been super busy lately so don't expect anything within the week.

**Comment by Earu** [comment]
Okay, so I've been messing around with the IBM API a bit, and it doesn't really seem very user-friendly for a non IT versed person. And I obviously cannot have one key that will be public and for everyone to use, for obvious security reasons. If anyone wants to write a simple document for a lambda user, on how to get a key off IBM's service you are more than welcome.

**Comment by Earu** [comment]
Since Yandex still works despite the keys being paid, and no proper alternative has been found I'm going to close this issue. Feel free to re-open a similar issue if you think you've found a better solution.
