### ISSUE TITLE
ULIB/ULX Related Error

### ISSUE THREAD

**Issue by johnnymoe** [Earu/EasyChat#62]
[ulib] lua/easychat/modules/cmds_auto_completion.lua:265: attempt to perform arithmetic on local 'arg_w' (a nil value)
  1. fn - lua/easychat/modules/cmds_auto_completion.lua:265
   2. unknown - addons/ulib/lua/ulib/shared/hook.lua:109 (x16)

Thanks for checking this out.

**Comment by Earu** [comment]
There seems to be cases with `draw.WordBox` returning nil, which isn't documented nor seem to be a common issue. While I've added a check for that please ensure that ULX is properly installed and you do not have any wonky addon.

**Comment by johnnymoe** [comment]
The problem is resolved. Thank you so much!
