### ISSUE TITLE
Autocompletion handles uppercase in commands incorrectly

### ISSUE THREAD

**Issue by stepa2** [Earu/EasyChat#63]
Probably no chat entry is matched with uppercase parts of the command.

### Example code:
`EasyChat.CmdSuggestions:AddSuggestionHandler("Example","/", {ABC = {}, ZABC = {}, Abc = {}, ZAbc = {}, Zabc = {}, abc = {}, zabc = {}})`
(run with lua_run_cl)

### Behaviour (all suggestions are in original order):
* When entry is `/`, suggestions are `/ABC`, `/abc`, `/ZABC`, `/ZAbc`, `/Zabc`, `/abc`, `/zabc`
* When entry is `/a` in any case, suggestions are `/Zabc`, `/abc`, `/zabc`  (`/ABC`, `/ZABC` and `/ZAbc` are missing)
* When entry is `/z` in any case, suggestion is `/zabc` (`/ZABC` and `/ZAbc` are missing)
* When entry is `/b` in any case, suggestions are `/Abc`, `/ZAbc`, `/Zabc`, `/abc`, `/zabc` (`/ABC`, `/ZABC` and `/ZAbc` are missing)
* When entry is `/c` in any case, suggestions are `/Abc`, `/ZAbc`, `/Zabc`, `/abc`, `/zabc` (`/ABC`, `/ZABC` and `/ZAbc` are missing)
* When entry is `/ab` in any case, suggestions are `/Zabc`, `/abc`, `/zabc` (`/ABC`, `/ZABC` and `/ZAbc` are missing)
* When entry is `/bc` in any case, suggestions are `/Abc`, `/ZAbc`, `/Zabc`, `/abc`, `/zabc` (`/ABC`, `/ZABC` and `/ZAbc` are missing)
* When entry is `/abc` in any case, suggestion is `/Zabc`, `/abc`, `/zabc` (`/ABC`, `/ZABC` and `/ZAbc` are missing)

**Comment by Earu** [comment]
Nice finding! I think the issue is fixed now, could you try again?

**Comment by stepa2** [comment]
It works now
