### ISSUE TITLE
easychat_only_local oversights

### ISSUE THREAD

**Issue by Cynosphere** [Earu/EasyChat#64]
Mainly just greentext found so far but theres probably other text modifying modules that don't have checks

**Comment by Earu** [comment]
@Cynosphere I'm not sure I understand fully the issue, what happens with greentext and local? Does it not add the (Local) tag or ?

**Comment by Cynosphere** [comment]
Could either move Only Local to base (not ideal without gamemode checks or what not) or just check if the convar exists and if its active and local chat. Other than that, I didn't realize it was meta-specific and thought it was apart of base.

**Comment by Earu** [comment]
I've moved the module inside EasyChat where it makes the most sense: https://github.com/Earu/EasyChat/commit/7a33a6b6bbf5353ad1045a79fd8591ca50196e9e
