### ISSUE TITLE
EasyChat keeps reporting out of date even when updated.

### ISSUE THREAD

**Issue by johnnymoe** [Earu/EasyChat#65]

**Comment by Earu** [comment]
Hey, are you running the GitHub version? If so are you using git or do you just download the zip archive?

It's possible that the cookie responsible for the version got corrupted, you could look into the `sv.db` file with [this software](https://sqlitebrowser.org/), and check for `ECLatestSHA` then delete the corresponding row.

If it doesn't fix the issue, you can always disable the version warning with `easychat_version_warnings 0` in your server's console.

**Comment by johnnymoe** [comment]
Thanks!
