### ISSUE TITLE
Module disabling

### ISSUE THREAD

**Issue by bronemishka** [Earu/EasyChat#66]
Is it possible to disable modules using commands, or with code?

**Comment by Earu** [comment]
You can simply remove the module related files and it should work

**Comment by bronemishka** [comment]
yeah, but to simplify updating process I want to use workshop version, which dont allow me to disable modules. So can I request feature to disable modules?)

**Comment by Earu** [comment]
I'll look into it

**Comment by Earu** [comment]
@bronemishka actually that sounds hardly doable with the current architecture, sorry.

**Comment by Earu** [comment]
https://github.com/Earu/EasyChat/commit/2e8392a3ad7ceb31da1975374a4a859fdb472173, after some insightful conversation with another developer we figured out how to do it. 

You should now be able to edit the `module ignore list` from settings > general. You will need to restart for these settings to take effect. Cheers!
