### ISSUE TITLE
Ignore Module file incorrectly exploding

### ISSUE THREAD

**Issue by KyleNaCl** [Earu/EasyChat#71]
when you load module_ignore_list.txt the contents do not get exploded properly and shows as 1 item in the table
```
1	=	easychat/modules/client/voice_hud.lua
easychat/modules/indications.lua
easychat/modules/join_leave.lua
```
i believe this is due to the extra parameters passed into 
`local lines = ("\r?\n"):Explode(file_contents)`
switching to 
`local lines = ("\n"):Explode(file_contents)`
fixes the current problem of wanting to ignore multiple modules

how the contents in my module_ignore_list.txt are listed
```
easychat/modules/client/voice_hud.lua
easychat/modules/indications.lua
easychat/modules/join_leave.lua
```

I also have noticed when you have multiple modules ignored, the list in the easychat settings menu doesn't list them all, more than likely due to the same issue of not exploding the file properly
![Screenshot_1034](https://user-images.githubusercontent.com/27458204/126909564-db41d088-e298-4f7f-ab91-194e6e1763fd.png)

**Comment by Earu** [comment]
Thank you for that report, I’ll see what I can do

**Comment by Earu** [comment]
https://github.com/Earu/EasyChat/commit/946e36ad8b412d235138afc9a8b1ee1b1edc49fe
