### ISSUE TITLE
Emoticon Code

### ISSUE THREAD

**Issue by asupreme1337** [Earu/EasyChat#73]
Hi, it's me again :)
I looked at all the settings, but I couldn't find any disabling of displaying the code of the sent smiley in the chat. The smiley is displayed only when the chat window is closed, and if you open it, you can only see the code that really interferes.

Is it possible to fix this?
Thanks.

![Screen](https://i.imgur.com/rFJVOab.png)

**Comment by Earu** [comment]
Hi this is not a bug, this is intended.
1) Because rendering every chat tag in the chat history would be too intensive.
2) Because it also shows other players how to use tags. That way everybody can learn just by watching others.

**Comment by asupreme1337** [comment]
Oh, I agree, it's really useful.
But it could be done like this:
1. The emotion would be displayed in the chat for a while, after which it is changed into code.
2. In the chat history (last session history), this would also have the form of a code (as it is now).

Some users may not have time to view a smiley (emotion) sent by someone, it may be wrong.

**Comment by Earu** [comment]
The benefits of this feature would be very minor, and the technical debt behind implementing it is way too large to even consider it, sorry.
