### ISSUE TITLE
how to hide the chatbox from easychat?

### ISSUE THREAD

**Issue by Pdzly** [Earu/EasyChat#77]
For programming how can i hide the chatbox so that no text popups? ( if someone sends you a text )

**Comment by Earu** [comment]
The `StartChat hook will prevent the chatbox from opening

**Comment by Pdzly** [comment]
too if someone other wrote something and normaly it lets the text pops in and fade away but "StartChat" hook will prevent it?

**Comment by Earu** [comment]
You can combine it with the ` HUDShouldDraw` to also suppress the chat hud.

**Comment by Pdzly** [comment]
but with HUDShouldDraw it can only hide default chat ?

**Comment by Earu** [comment]
No, it works with easychat too.
