### ISSUE TITLE
Error with starfall

### ISSUE THREAD

**Issue by licen150** [Earu/EasyChat#79]
Hello, when i trying to spawn a starfall chip he spawns but in console i see this error:
addons/easychat/lua/easychat/easychat.lua:755: Regex is too complex! 2 ext search length too long (500 max)
Starfall HUD enabled by licen777. NOTE: Type 'sf_hud_unlink' in the console to disconnect yourself from all HUDs.

Can you fix this please?

**Comment by licen150** [comment]
Install StarfallEX and EasyChat and and I think you can repeat

**Comment by Earu** [comment]
I still won't be able to reproduce it because starfall is a lua sandbox, so I need the lua code that causes this to replicate it.

**Comment by Earu** [comment]
Also follow-up: `Regex is too complex!` is not an error from either EasyChat or the vanilla game, so I can say first-hand that its very unlikely that EasyChat has anything to do with this.

**Comment by licen150** [comment]
Он по каким то причинам не может отправить это сообщение: "Starfall HUD enabled by licen777. NOTE: Type 'sf_hud_unlink' in the console to disconnect yourself from all HUDs." Here is the lua code https://pastebin.com/F5n12QF1

**Comment by licen150** [comment]
For some reason he cannot send this message: "Starfall HUD enabled by licen777. NOTE: Type 'sf_hud_unlink' in the console to disconnect yourself from all HUDs."  Here is the lua code: https://pastebin.com/F5n12QF1

**Comment by Earu** [comment]
I ran
```lua
local owner = LocalPlayer()
local enabledBy = owner and owner:IsValid() and (" by ".. owner:Nick()) or ""
LocalPlayer():ChatPrint("Starfall HUD enabled"..enabledBy..". NOTE: Type 'sf_hud_unlink' in the console to disconnect yourself from all HUDs.")```

Which is the equivalent of what is being ran when starfall runs the hud thing you have there. There is no error at all when I run it. However when I use a starfall chip with your code it does happen. 

Either way I the problem isnt coming from EasyChat.

**Comment by licen150** [comment]
https://youtu.be/xkv7QWKhae0

**Comment by Earu** [comment]
This is **not** an EasyChat problem, it's a starfall problem at most. Their repository is there: https://github.com/thegrb93/StarfallEx
