### ISSUE TITLE
Starfall module Error

### ISSUE THREAD

**Issue by KyleNaCl** [Earu/EasyChat#80]
Due to my server not having starfall installed, there is a lua error everytime there its a chat message sent

`lua/easychat/modules/client/starfall_compat.lua:19: attempt to index field 'SF' (a nil value)`

```
hook.Add("ECPostAddText", TAG, function()
	_G.SF.runningOps = previous_ops_state
end)
```
This hook just needs a check for if "SF" is valid

For now I can just disable this module to fix it

**Comment by Earu** [comment]
Thank you for the heads-up, it's now fixed, see https://github.com/Earu/EasyChat/commit/f834f2c3a605634fd74f8c1f783c191d2e21e8af
