### ISSUE TITLE
Sourcenet Requirement for EasyChat?

### ISSUE THREAD

**Issue by DOTD100** [Earu/EasyChat#81]
When I was launching a dedicated server, I saw a line saying that if I needed console command, sourcenet or slog was required to be installed. However, I followed the link to Sourcenet (gm_sourcenet) and couldn't find a way to install it. Could someone help me? Thanks!

**Comment by Earu** [comment]
Slog or sourcenet are required if you want your players messages sent via the `say` or `say_team` to be networked and included properly within EasyChat. It is not a requirement, just a "bonus" of sorts.

**Comment by DOTD100** [comment]
Thats quite a quick answer, I appreciate that. Also, I noticed that is for linux, but I'm running it on Windows. Because of that, I'm currently using gmsv_sourcenet_win32.dll in lua/bin. This should be it right?

**Comment by Earu** [comment]
That's correct yeah 👍
