### ISSUE TITLE
Can't see other players' messages.

### ISSUE THREAD

**Issue by KekkyShmekky** [Earu/EasyChat#82]
As per your request, I have opened the issue here. 

I have used Addon Conflict Hooks Finder and have found nothing that could interfere with EasyChat.
If you know of any other ways to check for conflicts that don't involve deleting addons, I'm all ears.

**Comment by Earu** [comment]
Thank you. Could you describe the problem in details? Also it seemed as you were only having that problem with messages sent by the server at one point, is it every message or just the server messages?

**Comment by KekkyShmekky** [comment]
When I did "say testing" in console with the EasyChat's custom HUD disabled, I could see the console's text but not text from other players.

**Comment by Earu** [comment]
Do you have a list of addons you use on your server I can look into?
Because so far I'm unable to reproduce this problem 
![image](https://user-images.githubusercontent.com/20880060/145030990-0d5694bf-62a0-48af-92f9-b9af62fc6c9f.png)

**Comment by KekkyShmekky** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=1648401086
<img width="604" alt="Screen Shot 2021-12-07 at 7 49 09 AM" src="https://user-images.githubusercontent.com/35896580/145031927-bb72bec2-207e-45b5-8149-4e8546744abf.png">

**Comment by Earu** [comment]
Have you checked "actchatcommands" ? Also have you tried to switch your server to another gamemode to be sure it wasnt the gamemode?

**Comment by KekkyShmekky** [comment]
Trying that now

**Comment by KekkyShmekky** [comment]
Hey so I actually just got around to removing actchatcommands, switching to Sandbox, and nothing worked

**Comment by KekkyShmekky** [comment]
Event "OnPlayerChat", GAMEMODE,
 in "lua/easychat/easychat.lua" (lines 2924 to 2966),
 found in Workshop addon « EasyChat », returned:
	Arg #1 = true

Ran a clientside conflict finder and it keeps returning true, which unless I'm mistaken in this case, suppresses the message.

**Comment by Earu** [comment]
Your conflict finder is finding a GAMEMODE function which is not a hook. The default return of OnPlayerChat is true which is the case here as expected.

**Comment by Earu** [comment]
Since I can't reproduce this problem on my end here's something that you can do:
Remove everything except your gamemode, check that it works.
If it does, add back each addon until it doesn't work anymore.

When you've found the culprit I can take a look at it again, until then there's nothing I can do. 🙁

**Comment by Earu** [comment]
I was just thinking of something, your server is a dedicated one right? Because the server console won't print player messages in there if it's not dedicated.

**Comment by KekkyShmekky** [comment]
Server is dedicated, messages were not local, PlayerCanSeePlayerChat returned this:
```
Event "PlayerCanSeePlayersChat", GAMEMODE,
 in "gamemodes/base/gamemode/player.lua" (lines 747 to 756),
 not found in Workshop addons, returned:
        Arg #1 = true
```
I printed MsgC() in console and it returned a blank line.
Some other addons use MsgC, but I doubt that should mean they're to blame.

I've also noticed the console messages print into a chat that's visually "behind" EasyChat. Not sure if this is intended.

**Comment by Earu** [comment]
>I've also noticed the console messages print into a chat that's visually "behind" EasyChat. Not sure if this is intended.

The chat you're talking about is probably the default source chat, you can't really remove it, and it's useful if you want to disable easychat on your client.

>I printed MsgC() in console and it returned a blank line.

MsgC is a function that allows you to make colorful messages in the console, so if you pass no arguments it will print a blank line for sure. 

>Some other addons use MsgC, but I doubt that should mean they're to blame.

I agree with you, using MsgC won't do anything particularly unexpected, however it would be useful to check if that function has been detoured by any addon you may have installed or the gamemode you're playing on.

>```
>Event "PlayerCanSeePlayersChat", GAMEMODE,
 >in "gamemodes/base/gamemode/player.lua" (lines 747 to 756),
 >not found in Workshop addons, returned:
  >      Arg #1 = true```

Could you past here the hook content of this?

**Comment by KekkyShmekky** [comment]
```
function GM:PlayerCanSeePlayersChat( strText, bTeamOnly, pListener, pSpeaker )

	if ( bTeamOnly ) then
		if ( !IsValid( pSpeaker ) || !IsValid( pListener ) ) then return false end
		if ( pListener:Team() != pSpeaker:Team() ) then return false end
	end

	return true

end
```

**Comment by Earu** [comment]
Alright well this seems pretty normal. I don't have any other leads for now.

**Comment by KekkyShmekky** [comment]
Actually I noticed you made a function local. Gonna test this on the next player that joins, unless you'd like to test it with me. My Discord is >KEKSQUAD#7054. IP is in the bio.

**Comment by Earu** [comment]
@KekkyShmekky Do you still need me to test this bug out with you, did my change fix your issue?

**Comment by Earu** [comment]
Seeing the lack of response I'm gonna assume it's fixed, if it isn't please open a new issue.
