### ISSUE TITLE
Hey!

### ISSUE THREAD

**Issue by Piehthyte** [Earu/EasyChat#83]
Hey I notice you're having issue with your workshop runner. You are running on windows, the latest one from 7 months ago ran properly on ubuntu.

**Comment by Earu** [comment]
@Piehthyte Yeah I'm aware, this is the new version of my workshop action that I'm desperately trying to get to work, it only runs on windows as well. But thanks for trying to help 😉

**Comment by Piehthyte** [comment]
> 

No problem, I hope you get it working!! Good luck
