### ISSUE TITLE
Murder

### ISSUE THREAD

**Issue by truepickisdead** [Earu/EasyChat#9]
Can u fix it for murder?
https://i.imgur.com/xQXmVba.gif

**Comment by Earu** [comment]
Honestly I've been looking on how to fix this issue in Murder, but the code for the gamemode is so bad, its really hard to figure out whats going on. But I checked it should at least work while you are playing, spectating doesnt work.

**Comment by Earu** [comment]
This was fixed in https://github.com/Earu/EasyChat/commit/de875da9e53648d0ca1ed611042affb22ca84239
