### ISSUE TITLE
EZ Chat

### ISSUE THREAD

**Issue by pkmnmstr98** [Earu/EasyChat#95]
EZ chat but no EZ linux/windows 64bit slog/gm_sourcenet . Could you possibly include a 64bit build ?

**Comment by Earu** [comment]
The best solution for you is to compile these modules yourself (one or the other) as the binary provided there might not work on every linux distro. I just do it as convenience because most servers run a variant of debian on the x86 branch. I could definitely include the Windows binaries though.

**Comment by pkmnmstr98** [comment]
Was able to build it! :) Also, if you do use sourcenet you must include the lua files from the project into the addons lmao.
Here are the commands for anyone else looking to build 64bit. Dont forget to change the garrysmod_common gen version before premake and obviously download premake5.

git clone --recursive -b x86-64-support-sourcesdk https://github.com/danielga/garrysmod_common.git
git clone --recursive -b update-lua-code https://github.com/danielga/gm_sourcenet.git
cd gm_sourcenet
 ./premake5 --gmcommon=/home/garrysmod_common gmake
cd projects/linux/gmake
make config=releasewithsymbols_x86_64
